local_backend: true

backend:
  name: git-gateway
  branch: master
  squash_merges: true

# display_url:
logo_url: /media/brand/logo.svg
media_folder: "static/media/uploads"
public_folder: "/media/uploads"
# publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "articles"
    label: "Articles"
    label_singular: "article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"

    # This is hack to remove index.md from the list. Add tag "article" to all articles except the index, and show only pages with this tag.
    filter: {field: "tags", value: "article"}

    # Enable this for a prewiew on the right when editing. You will have to create a preview template for it to make sense.
    editor:
      preview: false

    # more about widgets: https://www.netlifycms.org/docs/widgets/
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", allow_multiple: false}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["article"]}

  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: Site settings
        name: site-settings
        file: config.toml
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Google Analytics ID"
            name: "googleAnalytics"
            widget: "string"
          - label: "Params"
            name: "params"
            widget: "object"
            fields:
              - {label: "Description", name: "description", widget: "string"}
